// FROM [dbo].[sys_links]
export enum PermissionsList {
  ROLES_CREATE = 11,
  ROLES_EDIT = 12,
  ROLES_EXPORT = 13,
  COMPANIES_CREATE = 14,
  COMPANIES_EDIT = 15,
  COMPANIES_EXPORT = 16,
  USERS_CREATE = 17,
  USERS_EDIT = 18,
  USERS_EXPORT = 19,
  UOM_CREATE = 20,
  UOM_EDIT = 21,
  UOM_EXPORT = 22,
  BRANDS_CREATE = 23,
  BRANDS_EDIT = 24,
  BRANDS_EXPORT = 25,
}