// FROM [dbo].[sys_links]
export enum PermissionsList {
  ROLES_CREATE = 11,
  ROLES_EDIT = 12,
  ROLES_EXPORT = 13,
  COMPANIES_CREATE = 14,
  COMPANIES_EDIT = 15,
  COMPANIES_EXPORT = 16,
  USERS_CREATE = 17,
  USERS_EDIT = 18,
  USERS_EXPORT = 19,
}